{ ... }:

let
  colors = import ../colors;
  base_dir = ".ksk/scripts/";

  export = color: name: "THEME_${name}=${colors.utils.hsvToHex color}";
in with colors; {
  home.file = {
    ${base_dir + "colors.sh"}.text = ''
      #!/usr/bin/env bash
      # This file is autogenerated! Do not edit!

      export \
          ${export theme.bg0 "BG0"} \
          ${export theme.bg1 "BG1"} \
          ${export theme.bg2 "BG2"} \
          ${export theme.bgMin "BG_MIN"} \
          \
          ${export theme.hl1 "HL1"} \
          ${export theme.hl2 "HL2"} \
          ${export theme.hl3 "HL3"} \
          \
          ${export theme.fg1 "FG1"} \
          ${export theme.fg2 "FG2"} \
          ${export theme.fg3 "FG3"}
    '';
    ${base_dir + "lock.sh"}.source = ./lock.sh;
  };
}
